/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/porsche.glb --types --meta 
Author: Car2022 (https://sketchfab.com/Car2022)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-macan-ddce606aeef74ae485cbfebc4e34add2
Title: Porsche Macan
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    Object_11: THREE.Mesh
    Object_14: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_28: THREE.Mesh
    Object_31: THREE.Mesh
    Object_34: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
    Object_50: THREE.Mesh
    Object_53: THREE.Mesh
    Object_56: THREE.Mesh
    Object_59: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_71: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_83: THREE.Mesh
    Object_86: THREE.Mesh
    Object_89: THREE.Mesh
    Object_92: THREE.Mesh
    Object_95: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_107: THREE.Mesh
    Object_110: THREE.Mesh
    Object_113: THREE.Mesh
    Object_116: THREE.Mesh
    Object_119: THREE.Mesh
    Object_122: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_138: THREE.Mesh
    Object_141: THREE.Mesh
    Object_144: THREE.Mesh
    Object_147: THREE.Mesh
    Object_150: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_157: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_175: THREE.Mesh
    Object_178: THREE.Mesh
    Object_181: THREE.Mesh
    Object_184: THREE.Mesh
    Object_187: THREE.Mesh
    Object_190: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_200: THREE.Mesh
    Object_203: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_212: THREE.Mesh
    Object_215: THREE.Mesh
    Object_218: THREE.Mesh
    Object_221: THREE.Mesh
    Object_224: THREE.Mesh
    Object_227: THREE.Mesh
    Object_230: THREE.Mesh
    Object_233: THREE.Mesh
    Object_236: THREE.Mesh
    Object_239: THREE.Mesh
    Object_242: THREE.Mesh
    Object_245: THREE.Mesh
    Object_248: THREE.Mesh
    Object_251: THREE.Mesh
    Object_254: THREE.Mesh
    Object_256: THREE.Mesh
    Object_258: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_266: THREE.Mesh
    Object_268: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_287: THREE.Mesh
    Object_290: THREE.Mesh
    Object_293: THREE.Mesh
    Object_296: THREE.Mesh
    Object_299: THREE.Mesh
    Object_301: THREE.Mesh
    Object_304: THREE.Mesh
    Object_307: THREE.Mesh
    Object_310: THREE.Mesh
    Object_313: THREE.Mesh
    Object_316: THREE.Mesh
    Object_318: THREE.Mesh
    Object_320: THREE.Mesh
    Object_322: THREE.Mesh
    Object_324: THREE.Mesh
    Object_326: THREE.Mesh
    Object_328: THREE.Mesh
    Object_330: THREE.Mesh
    Object_332: THREE.Mesh
    Object_334: THREE.Mesh
    Object_336: THREE.Mesh
    Object_338: THREE.Mesh
    Object_340: THREE.Mesh
    Object_342: THREE.Mesh
    Object_344: THREE.Mesh
    Object_346: THREE.Mesh
    Object_348: THREE.Mesh
    Object_351: THREE.Mesh
    Object_354: THREE.Mesh
    Object_356: THREE.Mesh
    Object_358: THREE.Mesh
    Object_360: THREE.Mesh
    Object_362: THREE.Mesh
    Object_364: THREE.Mesh
    Object_366: THREE.Mesh
    Object_368: THREE.Mesh
    Object_370: THREE.Mesh
    Object_373: THREE.Mesh
    Object_376: THREE.Mesh
    Object_378: THREE.Mesh
    Object_380: THREE.Mesh
    Object_382: THREE.Mesh
    Object_384: THREE.Mesh
    Object_386: THREE.Mesh
    Object_388: THREE.Mesh
    Object_390: THREE.Mesh
    Object_392: THREE.Mesh
    Object_395: THREE.Mesh
    Object_397: THREE.Mesh
    Object_399: THREE.Mesh
    Object_401: THREE.Mesh
    Object_404: THREE.Mesh
    Object_407: THREE.Mesh
    Object_410: THREE.Mesh
    Object_413: THREE.Mesh
    Object_416: THREE.Mesh
    Object_419: THREE.Mesh
    Object_422: THREE.Mesh
    Object_425: THREE.Mesh
    Object_428: THREE.Mesh
    Object_431: THREE.Mesh
    Object_434: THREE.Mesh
    Object_437: THREE.Mesh
    Object_440: THREE.Mesh
    Object_443: THREE.Mesh
    Object_445: THREE.Mesh
    Object_447: THREE.Mesh
    Object_449: THREE.Mesh
    Object_451: THREE.Mesh
    Object_453: THREE.Mesh
    Object_455: THREE.Mesh
    Object_457: THREE.Mesh
    Object_460: THREE.Mesh
    Object_463: THREE.Mesh
    Object_466: THREE.Mesh
    Object_469: THREE.Mesh
    Object_471: THREE.Mesh
    Object_473: THREE.Mesh
    Object_475: THREE.Mesh
    Object_478: THREE.Mesh
    Object_481: THREE.Mesh
    Object_484: THREE.Mesh
    Object_487: THREE.Mesh
    Object_490: THREE.Mesh
    Object_493: THREE.Mesh
    Object_496: THREE.Mesh
    Object_499: THREE.Mesh
    Object_502: THREE.Mesh
    Object_505: THREE.Mesh
    Object_508: THREE.Mesh
    Object_511: THREE.Mesh
    Object_514: THREE.Mesh
    Object_517: THREE.Mesh
    Object_520: THREE.Mesh
    Object_522: THREE.Mesh
    Object_524: THREE.Mesh
    Object_526: THREE.Mesh
    Object_529: THREE.Mesh
    Object_532: THREE.Mesh
    Object_535: THREE.Mesh
    Object_538: THREE.Mesh
  }
  materials: {
    FWHEEL_M1: THREE.MeshStandardMaterial
    FCHROME5: THREE.MeshStandardMaterial
    FPL_BLACK5: THREE.MeshStandardMaterial
    FLIGHTS_R1: THREE.MeshStandardMaterial
    FCHASSIS10: THREE.MeshStandardMaterial
    FGLASS5: THREE.MeshStandardMaterial
    FALGO1: THREE.MeshStandardMaterial
    FWHEEL_MAT1: THREE.MeshStandardMaterial
    FWHEEL_BAD1: THREE.MeshStandardMaterial
    FCOLOR13: THREE.MeshPhysicalMaterial
    FMIRRORS1: THREE.MeshStandardMaterial
    FLIGHTS_F1: THREE.MeshStandardMaterial
    FBumperFront_XSG1: THREE.MeshStandardMaterial
    FBumperFront_A_FendersFront_BSG5: THREE.MeshStandardMaterial
    FR_GLAS_LIGHTS1: THREE.MeshStandardMaterial
    FAN_BADGES1: THREE.MeshStandardMaterial
    FALUM2: THREE.MeshStandardMaterial
    FBREAKS1: THREE.MeshStandardMaterial
    FPLAS_WHI1: THREE.MeshStandardMaterial
    FCUERO2: THREE.MeshStandardMaterial
    FTELA_I3: THREE.MeshStandardMaterial
    FAZUL1: THREE.MeshStandardMaterial
    FOTRO1: THREE.MeshStandardMaterial
    FChassis_XZSG6: THREE.MeshStandardMaterial
    FSEAT1: THREE.MeshStandardMaterial
    FRADIATOR2: THREE.MeshStandardMaterial
    FMET_P1: THREE.MeshStandardMaterial
    FROJOSATIN1: THREE.MeshStandardMaterial
    FLEAHT_BL1: THREE.MeshStandardMaterial
    FCARBON2: THREE.MeshPhysicalMaterial
    FHood_ASG2: THREE.MeshStandardMaterial
    FBumperRear_A_FendersRear_CSG4: THREE.MeshStandardMaterial
    FCOSTURAS1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/porsche.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'RootNode_2' }}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_8' }} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_11' }} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_14' }} />
        <group userData={{ name: 'F:Taillights_XTaillightsModelRigidbodyPOR_MacanTurbo_19_9' }}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.FCHROME5} userData={{ name: 'Object_17' }} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_19' }} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.FLIGHTS_R1} userData={{ name: 'Object_21' }} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_23' }} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.FGLASS5} userData={{ name: 'Object_25' }} />
        </group>
        <mesh geometry={nodes.Object_28.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_28' }} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_31' }} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_34' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19SuspensionFront_XSuspensionFront_21' }}>
          <mesh geometry={nodes.Object_37.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_37' }} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_39' }} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.FALGO1} userData={{ name: 'Object_41' }} />
        </group>
        <mesh geometry={nodes.Object_44.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_44' }} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_47' }} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_50' }} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_53' }} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_56' }} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_59' }} />
        <group userData={{ name: 'F:Wheel_Stock_POR_MacanTurbo_19_LOD0Wheel_Stock_POR_MacanTurbo_19_37' }}>
          <mesh geometry={nodes.Object_62.geometry} material={materials.FWHEEL_MAT1} userData={{ name: 'Object_62' }} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.FCHROME5} userData={{ name: 'Object_64' }} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.FWHEEL_BAD1} userData={{ name: 'Object_66' }} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_68' }} />
        </group>
        <mesh geometry={nodes.Object_71.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_71' }} />
        <group userData={{ name: 'F:Wheel_Stock_POR_MacanTurbo_19Wheel_Stock_POR_MacanTurbo_19_LOD1_44' }}>
          <mesh geometry={nodes.Object_74.geometry} material={materials.FWHEEL_MAT1} userData={{ name: 'Object_74' }} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.FCHROME5} userData={{ name: 'Object_76' }} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.FWHEEL_BAD1} userData={{ name: 'Object_78' }} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_80' }} />
        </group>
        <mesh geometry={nodes.Object_83.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_83' }} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_86' }} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_89' }} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_92' }} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_95' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Mirrors_XAMirrors_59' }}>
          <mesh geometry={nodes.Object_98.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_98' }} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.FGLASS5} userData={{ name: 'Object_100' }} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.FMIRRORS1} userData={{ name: 'Object_102' }} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.FLIGHTS_F1} userData={{ name: 'Object_104' }} />
        </group>
        <mesh geometry={nodes.Object_107.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_107' }} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_110' }} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_113' }} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_116' }} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_119' }} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_122' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19BumperFront_XBumperFront_76' }}>
          <mesh geometry={nodes.Object_125.geometry} material={materials.FBumperFront_XSG1} userData={{ name: 'Object_125' }} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_127' }} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_129' }} />
          <mesh geometry={nodes.Object_131.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_131' }} />
          <mesh geometry={nodes.Object_133.geometry} material={materials.FLIGHTS_F1} userData={{ name: 'Object_133' }} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.FBumperFront_A_FendersFront_BSG5} userData={{ name: 'Object_135' }} />
        </group>
        <mesh geometry={nodes.Object_138.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_138' }} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_141' }} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_144' }} />
        <mesh geometry={nodes.Object_147.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_147' }} />
        <mesh geometry={nodes.Object_150.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_150' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Roof_XZRoof_93' }}>
          <mesh geometry={nodes.Object_153.geometry} material={materials.FGLASS5} userData={{ name: 'Object_153' }} />
          <mesh geometry={nodes.Object_155.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_155' }} />
          <mesh geometry={nodes.Object_157.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_157' }} />
        </group>
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Trunk_ATrunk_97' }}>
          <mesh geometry={nodes.Object_160.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_160' }} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_162' }} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_164' }} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.FCHROME5} userData={{ name: 'Object_166' }} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.FLIGHTS_R1} userData={{ name: 'Object_168' }} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.FR_GLAS_LIGHTS1} userData={{ name: 'Object_170' }} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.FAN_BADGES1} userData={{ name: 'Object_172' }} />
        </group>
        <mesh geometry={nodes.Object_175.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_175' }} />
        <mesh geometry={nodes.Object_178.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_178' }} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_181' }} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_184' }} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_187' }} />
        <mesh geometry={nodes.Object_190.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_190' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Exhaust_XExhaust_117' }}>
          <mesh geometry={nodes.Object_193.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_193' }} />
          <mesh geometry={nodes.Object_195.geometry} material={materials.FALUM2} userData={{ name: 'Object_195' }} />
          <mesh geometry={nodes.Object_197.geometry} material={materials.FCHROME5} userData={{ name: 'Object_197' }} />
        </group>
        <mesh geometry={nodes.Object_200.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_200' }} />
        <group userData={{ name: 'F:Wheel_Stock_POR_MacanTurbo_19Wheel_Stock_POR_MacanTurbo_19_LOD2_123' }}>
          <mesh geometry={nodes.Object_203.geometry} material={materials.FWHEEL_MAT1} userData={{ name: 'Object_203' }} />
          <mesh geometry={nodes.Object_205.geometry} material={materials.FCHROME5} userData={{ name: 'Object_205' }} />
          <mesh geometry={nodes.Object_207.geometry} material={materials.FWHEEL_BAD1} userData={{ name: 'Object_207' }} />
          <mesh geometry={nodes.Object_209.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_209' }} />
        </group>
        <mesh geometry={nodes.Object_212.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_212' }} />
        <mesh geometry={nodes.Object_215.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_215' }} />
        <mesh geometry={nodes.Object_218.geometry} material={materials.FBREAKS1} userData={{ name: 'Object_218' }} />
        <mesh geometry={nodes.Object_221.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_221' }} />
        <mesh geometry={nodes.Object_224.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_224' }} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_227' }} />
        <mesh geometry={nodes.Object_230.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_230' }} />
        <mesh geometry={nodes.Object_233.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_233' }} />
        <mesh geometry={nodes.Object_236.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_236' }} />
        <mesh geometry={nodes.Object_239.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_239' }} />
        <mesh geometry={nodes.Object_242.geometry} material={materials.FBREAKS1} userData={{ name: 'Object_242' }} />
        <mesh geometry={nodes.Object_245.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_245' }} />
        <mesh geometry={nodes.Object_248.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_248' }} />
        <mesh geometry={nodes.Object_251.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_251' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Chassis_XZChassis_156' }}>
          <mesh geometry={nodes.Object_254.geometry} material={materials.FCHROME5} userData={{ name: 'Object_254' }} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_256' }} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_258' }} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.FAN_BADGES1} userData={{ name: 'Object_260' }} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_262' }} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.FALUM2} userData={{ name: 'Object_264' }} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.FPLAS_WHI1} userData={{ name: 'Object_266' }} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.FCUERO2} userData={{ name: 'Object_268' }} />
          <mesh geometry={nodes.Object_270.geometry} material={materials.FALGO1} userData={{ name: 'Object_270' }} />
          <mesh geometry={nodes.Object_272.geometry} material={materials.FTELA_I3} userData={{ name: 'Object_272' }} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.FAZUL1} userData={{ name: 'Object_274' }} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.FOTRO1} userData={{ name: 'Object_276' }} />
          <mesh geometry={nodes.Object_278.geometry} material={materials.FChassis_XZSG6} userData={{ name: 'Object_278' }} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.FSEAT1} userData={{ name: 'Object_280' }} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.FRADIATOR2} userData={{ name: 'Object_282' }} />
          <mesh geometry={nodes.Object_284.geometry} material={materials.FMET_P1} userData={{ name: 'Object_284' }} />
        </group>
        <mesh geometry={nodes.Object_287.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_287' }} />
        <mesh geometry={nodes.Object_290.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_290' }} />
        <mesh geometry={nodes.Object_293.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_293' }} />
        <mesh geometry={nodes.Object_296.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_296' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Sideskirts_XSideskirts_181' }}>
          <mesh geometry={nodes.Object_299.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_299' }} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_301' }} />
        </group>
        <mesh geometry={nodes.Object_304.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_304' }} />
        <mesh geometry={nodes.Object_307.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_307' }} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_310' }} />
        <mesh geometry={nodes.Object_313.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_313' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Interior_XInterior_192' }}>
          <mesh geometry={nodes.Object_316.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_316' }} />
          <mesh geometry={nodes.Object_318.geometry} material={materials.FGLASS5} userData={{ name: 'Object_318' }} />
          <mesh geometry={nodes.Object_320.geometry} material={materials.FOTRO1} userData={{ name: 'Object_320' }} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_322' }} />
          <mesh geometry={nodes.Object_324.geometry} material={materials.FCHROME5} userData={{ name: 'Object_324' }} />
          <mesh geometry={nodes.Object_326.geometry} material={materials.FCUERO2} userData={{ name: 'Object_326' }} />
          <mesh geometry={nodes.Object_328.geometry} material={materials.FTELA_I3} userData={{ name: 'Object_328' }} />
          <mesh geometry={nodes.Object_330.geometry} material={materials.FALUM2} userData={{ name: 'Object_330' }} />
          <mesh geometry={nodes.Object_332.geometry} material={materials.FSEAT1} userData={{ name: 'Object_332' }} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.FROJOSATIN1} userData={{ name: 'Object_334' }} />
          <mesh geometry={nodes.Object_336.geometry} material={materials.FLEAHT_BL1} userData={{ name: 'Object_336' }} />
          <mesh geometry={nodes.Object_338.geometry} material={materials.FCARBON2} userData={{ name: 'Object_338' }} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_340' }} />
          <mesh geometry={nodes.Object_342.geometry} material={materials.FALGO1} userData={{ name: 'Object_342' }} />
          <mesh geometry={nodes.Object_344.geometry} material={materials.FHood_ASG2} userData={{ name: 'Object_344' }} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.FMIRRORS1} userData={{ name: 'Object_346' }} />
          <mesh geometry={nodes.Object_348.geometry} material={materials.FAN_BADGES1} userData={{ name: 'Object_348' }} />
        </group>
        <mesh geometry={nodes.Object_351.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_351' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Doors_XDoors_212' }}>
          <mesh geometry={nodes.Object_354.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_354' }} />
          <mesh geometry={nodes.Object_356.geometry} material={materials.FCHROME5} userData={{ name: 'Object_356' }} />
          <mesh geometry={nodes.Object_358.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_358' }} />
          <mesh geometry={nodes.Object_360.geometry} material={materials.FCARBON2} userData={{ name: 'Object_360' }} />
          <mesh geometry={nodes.Object_362.geometry} material={materials.FCUERO2} userData={{ name: 'Object_362' }} />
          <mesh geometry={nodes.Object_364.geometry} material={materials.FBumperRear_A_FendersRear_CSG4} userData={{ name: 'Object_364' }} />
          <mesh geometry={nodes.Object_366.geometry} material={materials.FCOSTURAS1} userData={{ name: 'Object_366' }} />
          <mesh geometry={nodes.Object_368.geometry} material={materials.FAN_BADGES1} userData={{ name: 'Object_368' }} />
          <mesh geometry={nodes.Object_370.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_370' }} />
        </group>
        <mesh geometry={nodes.Object_373.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_373' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19BumperRear_XBumperRear_224' }}>
          <mesh geometry={nodes.Object_376.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_376' }} />
          <mesh geometry={nodes.Object_378.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_378' }} />
          <mesh geometry={nodes.Object_380.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_380' }} />
          <mesh geometry={nodes.Object_382.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_382' }} />
          <mesh geometry={nodes.Object_384.geometry} material={materials.FGLASS5} userData={{ name: 'Object_384' }} />
          <mesh geometry={nodes.Object_386.geometry} material={materials.FCHROME5} userData={{ name: 'Object_386' }} />
          <mesh geometry={nodes.Object_388.geometry} material={materials.FLIGHTS_R1} userData={{ name: 'Object_388' }} />
          <mesh geometry={nodes.Object_390.geometry} material={materials.FR_GLAS_LIGHTS1} userData={{ name: 'Object_390' }} />
          <mesh geometry={nodes.Object_392.geometry} material={materials.FBumperRear_A_FendersRear_CSG4} userData={{ name: 'Object_392' }} />
        </group>
        <group userData={{ name: 'F:Wheel_Stock_POR_MacanTurbo_19Wheel_Stock_POR_MacanTurbo_19_LOD3_234' }}>
          <mesh geometry={nodes.Object_395.geometry} material={materials.FWHEEL_MAT1} userData={{ name: 'Object_395' }} />
          <mesh geometry={nodes.Object_397.geometry} material={materials.FCHROME5} userData={{ name: 'Object_397' }} />
          <mesh geometry={nodes.Object_399.geometry} material={materials.FWHEEL_BAD1} userData={{ name: 'Object_399' }} />
          <mesh geometry={nodes.Object_401.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_401' }} />
        </group>
        <mesh geometry={nodes.Object_404.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_404' }} />
        <mesh geometry={nodes.Object_407.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_407' }} />
        <mesh geometry={nodes.Object_410.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_410' }} />
        <mesh geometry={nodes.Object_413.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_413' }} />
        <mesh geometry={nodes.Object_416.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_416' }} />
        <mesh geometry={nodes.Object_419.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_419' }} />
        <mesh geometry={nodes.Object_422.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_422' }} />
        <mesh geometry={nodes.Object_425.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_425' }} />
        <mesh geometry={nodes.Object_428.geometry} material={materials.FBREAKS1} userData={{ name: 'Object_428' }} />
        <mesh geometry={nodes.Object_431.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_431' }} />
        <mesh geometry={nodes.Object_434.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_434' }} />
        <mesh geometry={nodes.Object_437.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_437' }} />
        <mesh geometry={nodes.Object_440.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_440' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Headlights_XHeadlights_265' }}>
          <mesh geometry={nodes.Object_443.geometry} material={materials.FBumperFront_A_FendersFront_BSG5} userData={{ name: 'Object_443' }} />
          <mesh geometry={nodes.Object_445.geometry} material={materials.FGLASS5} userData={{ name: 'Object_445' }} />
          <mesh geometry={nodes.Object_447.geometry} material={materials.FLIGHTS_F1} userData={{ name: 'Object_447' }} />
          <mesh geometry={nodes.Object_449.geometry} material={materials.FALUM2} userData={{ name: 'Object_449' }} />
          <mesh geometry={nodes.Object_451.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_451' }} />
          <mesh geometry={nodes.Object_453.geometry} material={materials.FCHROME5} userData={{ name: 'Object_453' }} />
          <mesh geometry={nodes.Object_455.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_455' }} />
          <mesh geometry={nodes.Object_457.geometry} material={materials.FAN_BADGES1} userData={{ name: 'Object_457' }} />
        </group>
        <mesh geometry={nodes.Object_460.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_460' }} />
        <mesh geometry={nodes.Object_463.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_463' }} />
        <mesh geometry={nodes.Object_466.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_466' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19Hood_XHood_280' }}>
          <mesh geometry={nodes.Object_469.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_469' }} />
          <mesh geometry={nodes.Object_471.geometry} material={materials.FHood_ASG2} userData={{ name: 'Object_471' }} />
          <mesh geometry={nodes.Object_473.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_473' }} />
          <mesh geometry={nodes.Object_475.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_475' }} />
        </group>
        <mesh geometry={nodes.Object_478.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_478' }} />
        <mesh geometry={nodes.Object_481.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_481' }} />
        <mesh geometry={nodes.Object_484.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_484' }} />
        <mesh geometry={nodes.Object_487.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_487' }} />
        <mesh geometry={nodes.Object_490.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_490' }} />
        <mesh geometry={nodes.Object_493.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_493' }} />
        <mesh geometry={nodes.Object_496.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_496' }} />
        <mesh geometry={nodes.Object_499.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_499' }} />
        <mesh geometry={nodes.Object_502.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_502' }} />
        <mesh geometry={nodes.Object_505.geometry} material={materials.FCOLOR13} userData={{ name: 'Object_505' }} />
        <mesh geometry={nodes.Object_508.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_508' }} />
        <mesh geometry={nodes.Object_511.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_511' }} />
        <mesh geometry={nodes.Object_514.geometry} material={materials.FBREAKS1} userData={{ name: 'Object_514' }} />
        <mesh geometry={nodes.Object_517.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_517' }} />
        <group userData={{ name: 'F:ModelRigidbodyPOR_MacanTurbo_19SuspensionRear_XSuspensionRear_313' }}>
          <mesh geometry={nodes.Object_520.geometry} material={materials.FCHASSIS10} userData={{ name: 'Object_520' }} />
          <mesh geometry={nodes.Object_522.geometry} material={materials.FPL_BLACK5} userData={{ name: 'Object_522' }} />
          <mesh geometry={nodes.Object_524.geometry} material={materials.FALGO1} userData={{ name: 'Object_524' }} />
          <mesh geometry={nodes.Object_526.geometry} material={materials.FHood_ASG2} userData={{ name: 'Object_526' }} />
        </group>
        <mesh geometry={nodes.Object_529.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_529' }} />
        <mesh geometry={nodes.Object_532.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_532' }} />
        <mesh geometry={nodes.Object_535.geometry} material={materials.FGLASS5} userData={{ name: 'Object_535' }} />
        <mesh geometry={nodes.Object_538.geometry} material={materials.FWHEEL_M1} userData={{ name: 'Object_538' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/porsche.glb')
